# Desafio

### Exercício: Explorando o Conjunto de Dados de Vendas de Videogames

**Objetivo:** Utilizar a biblioteca Pandas para extrair e analisar informações dos conjuntos de dados de vendas de jogos e video games.


### Tarefas dos Alunos

1. **Leitura e Inspeção dos Dados:**
   - Carregue os arquivos CSV em DataFrames separados.
   - Combine os DataFrames em um único DataFrame.
   - Renomeie as colunas para português
   - Exiba as primeiras 5 linhas do DataFrame combinado.
   - Exiba informações gerais e estatísticas descritivas do DataFrame.

2. **Análise Exploratória:**
   - Conte a quantidade de jogos por plataforma.
   - Calcule a média das vendas globais por plataforma.
   - Conte a quantidade de jogos por gênero.

3. **Filtragem de Dados:**
   - Filtre os jogos com vendas globais acima da média e conte quantos são.
   - Filtre os jogos lançados após o ano 2010 e calcule a média das vendas globais desses jogos.

4. **Operações Avançadas:**
   - Adicione uma coluna ao DataFrame que calcule a soma das vendas na América do Norte e Europa.
   - Agrupe os dados por ano de lançamento e calcule a média das vendas globais.

In [1]:
#1.Leitura e Inspeção CSV em DataFrames separados.

##Carregue os arquivos CSV em DataFrames separados
import pandas as pd #importar a biblioteca para utilizar os métodos contidos nela

df_vendas_vg_a = pd.read_csv('/content/Video_Game_Sales_a.csv')
df_vendas_vg_b = pd.read_csv('/content/Video_Game_Sales_b.csv')

##Combine os DataFrames em um único DataFrame
df_vendas_vg = pd.concat([df_vendas_vg_a, df_vendas_vg_b])
#df_vendas_vg = df_vendas_vg_a + df_vendas_vg_b #(outra opção para analisar posteriormente)
print(df_vendas_vg.shape[0]) #qtd de linhas dos df concatenados
print(df_vendas_vg_a.shape[0]) #qtd de linhas do df_a
print(df_vendas_vg_b.shape[0]) #qtd de linhas do df_b

16597
16398
199

In [2]:
##Renomeie as colunas para português
df_vendas_vg.columns = ['Rank', 'Nome', 'Plataforma', 'Ano', 'Genero', 'Empresa', 'AmericaNorte_Vendas',
                      'Europa_Vendas', 'Japao_Sales', 'Outras_Vendas', 'Vendas_Globais']

df_vendas_vg.columns

Index(['Rank', 'Nome', 'Plataforma', 'Ano', 'Genero', 'Empresa',
       'AmericaNorte_Vendas', 'Europa_Vendas', 'Japao_Sales', 'Outras_Vendas',
       'Vendas_Globais'],
      dtype='object')

In [3]:
##Exiba as primeiras 5 linhas do DataFrame combinado.
df_vendas_vg.head()

,Rank,Nome,Plataforma,Ano,Genero,Empresa,AmericaNorte_Vendas,Europa_Vendas,Japao_Sales,Outras_Vendas,Vendas_Globais
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74;
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24;
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82;
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33;
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37;

In [4]:
##Exiba informações gerais e estatísticas descritivas do DataFrame.
print('=======================================================================')
print('informações tabela')
print(df_vendas_vg.info())
print('=======================================================================')
print('descrição tabela')
print(df_vendas_vg.describe())

=======================================================================
informações tabela
<class 'pandas.core.frame.DataFrame'>
Index: 16597 entries, 0 to 198
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rank                 16597 non-null  object
 1   Nome                 16474 non-null  object
 2   Plataforma           16474 non-null  object
 3   Ano                  16205 non-null  float64
 4   Genero               16474 non-null  object
 5   Empresa              16417 non-null  object
 6   AmericaNorte_Vendas  16474 non-null  float64
 7   Europa_Vendas        16474 non-null  float64
 8   Japao_Sales          16474 non-null  float64
 9   Outras_Vendas        16474 non-null  float64
 10  Vendas_Globais       16474 non-null  object
dtypes: float64(5), object(6)
memory usage: 1.5+ MB
None
=======================================================================
descrição tabela
                Ano  AmericaNorte_Vendas  Europa_Vendas   Japao_Sales  \
count  16205.000000         16474.000000   16474.000000  16474.000000
mean    2006.401851             0.265742       0.147347      0.078024
std        5.841352             0.819540       0.507088      0.310186
min     1980.000000             0.000000       0.000000      0.000000
25%     2003.000000             0.000000       0.000000      0.000000
50%     2007.000000             0.080000       0.020000      0.000000
75%     2010.000000             0.240000       0.110000      0.040000
max     2020.000000            41.490000      29.020000     10.220000

       Outras_Vendas
count   16474.000000
mean        0.048283
std         0.189257
min         0.000000
25%         0.000000
50%         0.010000
75%         0.040000
max        10.570000

In [5]:
#2.Análise Exploratória:

##Conte a quantidade de jogos por plataforma.
df_vendas_vg_no_dup = df_vendas_vg.drop_duplicates() #deleta linhas completemante semelhantes
jogos_por_platforma = df_vendas_vg['Plataforma'].value_counts()
jogos_por_platform_no_dup = df_vendas_vg_no_dup['Plataforma'].value_counts()
print(jogos_por_platforma)
print(jogos_por_platform_no_dup)

Plataforma
PS2     2144
DS      2137
PS3     1323
Wii     1317
X360    1258
PSP     1200
PS      1192
PC       951
XB       820
GBA      807
GC       551
3DS      506
PSV      411
PS4      336
N64      318
SNES     239
XOne     213
SAT      172
WiiU     143
2600     133
NES       98
GB        98
DC        50
GEN       26
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: count, dtype: int64
Plataforma
PS2     2144
DS      2137
PS3     1323
Wii     1317
X360    1258
PSP     1200
PS      1192
PC       951
XB       820
GBA      807
GC       551
3DS      506
PSV      411
PS4      336
N64      318
SNES     239
XOne     213
SAT      172
WiiU     143
2600     133
NES       98
GB        98
DC        50
GEN       26
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: count, dtype: int64

In [6]:

numero = '10;' #declarado como string

numero = numero.replace(';','')
print(numero)
#print(type(int(numero))) # string foi transformado em um inteiro
print(type(float(numero)))

10
<class 'float'>

In [15]:
##Calcule a média das vendas globais por plataforma.
###tratar a coluna Vendas Globais
#df_vendas_vg['Vendas_Globais'] = df_vendas_vg['Vendas_Globais'].str.replace(';','')
#type(df_vendas_vg['Vendas_Globais'].str)
df_vendas_vg['Vendas_Globais'] = pd.to_numeric(df_vendas_vg['Vendas_Globais'])
df_vendas_vg.dtypes
medias_vendas_globais = df_vendas_vg.groupby('Plataforma')['Vendas_Globais'].mean()
medias_vendas_globais

Genero
Action          3293
Sports          2340
Misc            1716
Role-Playing    1480
Shooter         1296
Adventure       1263
Racing          1246
Platform         878
Simulation       863
Fighting         847
Strategy         674
Puzzle           578
Name: count, dtype: int64

In [17]:
##Conte a quantidade de jogos por gênero.
jogo_por_genero = df_vendas_vg['Genero'].value_counts()
jogo_por_genero

Genero
Action          3293
Sports          2340
Misc            1716
Role-Playing    1480
Shooter         1296
Adventure       1263
Racing          1246
Platform         878
Simulation       863
Fighting         847
Strategy         674
Puzzle           578
Name: count, dtype: int64

In [28]:
#3. Filtragem de Dados:
media_vendas_globais = df_vendas_vg['Vendas_Globais'].mean()
media_vendas_globais
#Filtre os jogos com vendas globais acima da média e conte quantos são.
jogos_venda_acima_media = df_vendas_vg.loc[(df_vendas_vg['Vendas_Globais'] > media_vendas_globais)]
#jogos_venda_acima_media.shape[0]
print(len(jogos_venda_acima_media))

#Filtre os jogos lançados após o ano 2010 e calcule a média das vendas globais desses jogos.
ano_filtro = 2010
jogos_venda_maior_2010 = df_vendas_vg.loc[(df_vendas_vg['Ano'] > ano_filtro)]
jogos_venda_maior_2010['Vendas_Globais'].mean()

3741

0.49568140677527806

In [56]:
#4. Operações Avançadas:

#Adicione uma coluna ao DataFrame que calcule a soma das vendas na América do Norte e Europa.
df_vendas_vg['AN_EU_Vendas'] = df_vendas_vg['Europa_Vendas'] + df_vendas_vg['AmericaNorte_Vendas']
df_vendas_vg.columns
df_vendas_vg.head()

#Agrupe os dados por ano de lançamento e calcule a média das vendas globais.
media_vendas_globais_ano = df_vendas_vg.groupby('Ano')['Vendas_Globais'].mean()
media_vendas_globais_ano

Ano
1980.0    1.264444
1981.0    0.777609
1982.0    0.801667
1983.0    0.987647
1984.0    3.597143
1985.0    3.852857
1986.0    1.765238
1987.0    1.358750
1988.0    3.148000
1989.0    4.320588
1990.0    3.086875
1991.0    0.786098
1992.0    1.771163
1993.0    0.766333
1994.0    0.658583
1995.0    0.402329
1996.0    0.757224
1997.0    0.695433
1998.0    0.675532
1999.0    0.743402
2000.0    0.579712
2001.0    0.688431
2002.0    0.478967
2003.0    0.462943
2004.0    0.551605
2005.0    0.492168
2006.0    0.519232
2007.0    0.511341
2008.0    0.479272
2009.0    0.468670
2010.0    0.479784
2011.0    0.455484
2012.0    0.554162
2013.0    0.675394
2014.0    0.580103
2015.0    0.431358
2016.0    0.206735
2017.0    0.016667
2020.0    0.290000
Name: Vendas_Globais, dtype: float64